-- ==============================================================================
-- Seed: Official Audited Government Scheme Catalog (NSFDC / MoSJE)
-- Idempotent upsert script for SchemeBridge
-- Total Schemes: 8
-- ==============================================================================

INSERT INTO public.schemes (
    id,
    scheme_name,
    category,
    purpose_category,
    max_loan_amount,
    income_limit,
    interest_rate,
    interest_rate_text,
    govt_coverage_percent,
    promoter_margin_percent,
    moratorium_available,
    moratorium_details,
    repayment_period,
    target_beneficiaries,
    description,
    key_highlights,
    semantic_description,
    official_source,
    is_active
) VALUES
(
    'micro-finance-small',
    'Micro Credit Finance (MCF) Scheme',
    'MICRO',
    'business',
    140000.00,
    500000.00,
    6.50,
    '6.5% p.a.',
    90.00,
    10.00,
    TRUE,
    '3 Months Moratorium',
    'Up to 3 years (36 months) in quarterly installments',
    'Small artisans, street vendors, tailors, micro-business owners, petty shopkeepers belonging to Scheduled Castes',
    'Specially tailored micro-credit facility under NSFDC for small-scale entrepreneurs, artisans, and micro-business owners. Offers 90% direct financial assistance with minimal documentation.',
    '["Concessional interest rate of 6.5% per annum to beneficiaries (NSFDC charges 2.5% to SCAs)", "90% loan funded by NSFDC / Channel Partner Agency (max loan ₹1.25L - ₹1.26L per unit)", "Only 10% beneficiary promoter margin contribution required", "Repayment period of up to 3 years (36 months) in quarterly installments", "Includes 3-month initial moratorium period"]'::jsonb,
    'Micro Credit Finance scheme for micro businesses, petty shopkeepers, street vendors, small artisans, tailoring units, sewing machines, garment stitching, handicraft making, small equipment purchase, and working capital up to ₹1.40 Lakhs.',
    'NSFDC / MoSJE (https://nsfdc.nic.in - Micro Credit Finance)',
    TRUE
),
(
    'term-loan-nsfdc',
    'National Concessional Term Loan (TL) Scheme',
    'MEDIUM',
    'business',
    5000000.00,
    500000.00,
    8.00,
    '8.0% p.a.',
    90.00,
    10.00,
    TRUE,
    '6 Months Moratorium (12 months for plantation/construction)',
    'Up to 7 years (84 months) in quarterly installments',
    'SC commercial entrepreneurs, industrial units, expanding businesses, transport vehicle operators, equipment buyers',
    'Medium to large capital investment loan scheme designed for viable projects in industrial, agricultural, and service sectors, acquiring machinery, and commercial production.',
    '["Concessional interest rate of 8.0% per annum to beneficiaries (NSFDC charges 4% to SCAs)", "90% NSFDC loan funding coverage (up to ₹45.00 Lakhs on ₹50.00 Lakhs project cost)", "Promoter contribution fixed at minimum 10%", "Tenure of up to 7 years (84 months) in quarterly installments", "6-month initial moratorium period (12 months for plantation/construction)"]'::jsonb,
    'National Concessional Term Loan Scheme for medium to large business enterprises, industrial projects, acquiring heavy machinery, manufacturing equipment, setting up commercial service centers, transport vehicles, and factory expansion up to ₹50.00 Lakhs.',
    'NSFDC / MoSJE (https://nsfdc.nic.in - Term Loan Scheme)',
    TRUE
),
(
    'education-loan-scheme',
    'Educational Loan Scheme (ELS - Higher Studies)',
    'EDUCATION',
    'education',
    4000000.00,
    500000.00,
    6.50,
    '6.5% p.a. (6.0% for female students)',
    90.00,
    10.00,
    TRUE,
    'Course Duration + 1 Year Moratorium (or 6 months after securing job)',
    'Up to 5 to 10 years after moratorium period',
    'SC students pursuing full-time professional/technical courses (Engineering, Medical, Management, CA/CS, Research) in India and Abroad',
    'Comprehensive financial support for SC students pursuing full-time professional and technical studies in recognized institutions in India and abroad with zero repayment during study period.',
    '["Concessional interest rate of 6.5% p.a. with 0.5% rebate for female students (6.0% p.a.)", "Up to 90% total educational expense covered by NSFDC (up to ₹40.00 Lakhs)", "10% margin money requirement by promoter/student", "Moratorium benefit: Repayment starts only 1 year after course completion or 6 months after job", "Covers admission/tuition fees, books, equipment, hostel, exam, and travel expenses"]'::jsonb,
    'Subsidized Education Loan Scheme for students seeking financial assistance for higher education, university tuition fees, college degrees, professional and technical courses, engineering, medicine, management, higher studies abroad, textbooks, and hostel accommodation up to ₹40.00 Lakhs.',
    'NSFDC / MoSJE (https://nsfdc.nic.in - Educational Loan Scheme)',
    TRUE
),
(
    'mahila-samriddhi-yojana',
    'Mahila Samriddhi Yojana (MSY - Women Micro Credit)',
    'MICRO',
    'business',
    140000.00,
    500000.00,
    4.00,
    '4.0% p.a.',
    90.00,
    10.00,
    TRUE,
    '3 Months Moratorium',
    'Up to 3 years (36 months) in quarterly installments',
    'Women entrepreneurs, female artisans, women SHGs, tailoring, boutique, small livestock, micro retail',
    'Highly concessional micro-finance scheme specifically designed to empower women from the Scheduled Caste community by providing affordable credit for income-generating micro activities.',
    '["Ultra-low concessional interest rate of 4.0% per annum to women beneficiaries", "Up to 90% funding coverage (max loan ₹1.25L on ₹1.40L project cost)", "10% beneficiary promoter margin contribution", "Repayment period of up to 3 years with 3-month initial moratorium", "Direct financial empowerment for women artisans and micro-entrepreneurs"]'::jsonb,
    'Mahila Samriddhi Yojana micro credit scheme for women entrepreneurs, women self help groups, tailoring, boutique, handicrafts, small shops, beauty parlors, small livestock, and home-based micro businesses up to ₹1.40 Lakhs at 4% interest rate.',
    'NSFDC / MoSJE (https://nsfdc.nic.in - Mahila Samriddhi Yojana)',
    TRUE
),
(
    'laghu-vyavsay-yojana',
    'Laghu Vyavsay Yojana (LVY - Small Business Scheme)',
    'MEDIUM',
    'business',
    500000.00,
    500000.00,
    6.00,
    '6.0% p.a.',
    90.00,
    10.00,
    TRUE,
    '6 Months Moratorium',
    'Up to 5 years (60 months) in quarterly installments',
    'Dairy farmers, animal husbandry, small retail stores, vehicle repair workshops, rural service units',
    'Financial assistance under NSFDC for small commercial business units, dairy farming, milk booths, livestock rearing, retail shops, and commercial service establishments.',
    '["Subsidized interest rate of 6.0% per annum to beneficiaries (NSFDC charges 3% to SCAs)", "Supports dairy business, cattle purchase, milk production, and small retail shops", "90% funding coverage (up to ₹4.50 Lakhs loan on ₹5.00 Lakhs project cost)", "Promoter margin contribution fixed at 10%", "Flexible repayment terms up to 5 years with 6 months initial moratorium"]'::jsonb,
    'Laghu Vyavsay Yojana for small commercial businesses, dairy business, dairy farming, cattle purchase, livestock, milk production, grocery retail stores, workshop repair, photo studio, and small service enterprises up to ₹5.00 Lakhs.',
    'NSFDC / MoSJE (https://nsfdc.nic.in - Laghu Vyavsay Yojana)',
    TRUE
),
(
    'green-business-scheme',
    'Green Business Scheme (GBS - Eco & Renewable Ventures)',
    'MEDIUM',
    'business',
    3000000.00,
    500000.00,
    6.00,
    '4.0% - 7.0% p.a. (1% rebate for women)',
    90.00,
    10.00,
    TRUE,
    '6 Months Moratorium',
    'Up to 7 to 10 years in quarterly installments',
    'SC entrepreneurs setting up climate-mitigation green units, solar energy, e-rickshaws, organic farming, polyhouses',
    'Financial assistance for income-generating activities that address climate change, including battery-operated e-rickshaws, solar rooftop units/pumps, polyhouses, and waste recycling.',
    '["Concessional interest rate: 4% p.a. (up to ₹7.5L), 6% p.a. (₹7.5L-₹15L), 7% p.a. (₹15L-₹30L)", "1% interest rebate per annum for women beneficiaries", "Up to 90% loan funded by NSFDC (up to ₹27.00 Lakhs on ₹30.00 Lakhs unit cost)", "10% promoter margin contribution", "Repayment tenure of up to 7 to 10 years including 6 months moratorium"]'::jsonb,
    'Green Business Scheme for climate change mitigation, electric rickshaw, battery vehicles, solar rooftop units, solar pumps, polyhouses, organic farming, waste recycling, and renewable green energy projects up to ₹30.00 Lakhs.',
    'NSFDC / MoSJE (https://dosje.gov.in & https://myscheme.gov.in - Green Business Scheme)',
    TRUE
),
(
    'swachhta-udyami-yojana',
    'Swachhta Udyami Yojana (SUY - Sanitation Mechanization)',
    'LARGE',
    'business',
    5000000.00,
    500000.00,
    4.00,
    '4.0% p.a. (1% rebate for women)',
    90.00,
    10.00,
    TRUE,
    '6 Months Moratorium',
    'Up to 7 years (84 months) in quarterly installments',
    'Safai Karamcharis, manual scavengers rehabilitation, sanitation entrepreneurs, waste management operators',
    'Financial assistance for the procurement and operation of mechanized sanitation equipment, vacuum cleaning loaders, suction trucks, and garbage transport to eliminate manual scavenging.',
    '["Highly concessional interest rate of 4.0% per annum (with 1% rebate for women)", "Up to 90% loan funding coverage by NSFDC (up to ₹45.00 Lakhs on ₹50.00 Lakhs project cost)", "Promoter margin contribution of 10%", "Tenure of up to 7 years (84 months) in quarterly installments", "6-month initial moratorium period included"]'::jsonb,
    'Swachhta Udyami Yojana for mechanized sanitation equipment, vacuum loader trucks, suction machines, septic tank cleaning vehicles, garbage collection transport, and public hygiene infrastructure up to ₹50.00 Lakhs.',
    'NSFDC / NSKFDC / MoSJE (https://dosje.gov.in & https://myscheme.gov.in - Swachhta Udyami Yojana)',
    TRUE
),
(
    'micro-finance-education',
    'Micro Credit Finance - Skill & Vocational Training',
    'MICRO',
    'education',
    140000.00,
    500000.00,
    6.50,
    '6.5% p.a.',
    90.00,
    10.00,
    TRUE,
    'Course Duration Moratorium',
    'Up to 3 years (36 months) in quarterly installments',
    'SC students undergoing short-term vocational diplomas, ITI, skill certifications, NSDC programs',
    'Micro-credit support under NSFDC for vocational training, skill enhancement, short-term computer courses, diploma certifications, and technical equipment.',
    '["Concessional interest rate of 6.5% p.a. to beneficiaries", "Up to 90% funding coverage (max loan ₹1.25L - ₹1.26L)", "Covers short-term vocational diplomas, ITI, computer hardware and coding certificates", "Minimal documentation with zero collateral"]'::jsonb,
    'Micro Credit Finance for vocational courses, technical training, computer diploma, ITI certifications, skill development programs, short-term certification courses, and learning equipment up to ₹1.40 Lakhs.',
    'NSFDC / MoSJE (https://nsfdc.nic.in - Skill Development & Micro Finance)',
    TRUE
)
ON CONFLICT (id) DO UPDATE SET
    scheme_name = EXCLUDED.scheme_name,
    category = EXCLUDED.category,
    purpose_category = EXCLUDED.purpose_category,
    max_loan_amount = EXCLUDED.max_loan_amount,
    income_limit = EXCLUDED.income_limit,
    interest_rate = EXCLUDED.interest_rate,
    interest_rate_text = EXCLUDED.interest_rate_text,
    govt_coverage_percent = EXCLUDED.govt_coverage_percent,
    promoter_margin_percent = EXCLUDED.promoter_margin_percent,
    moratorium_available = EXCLUDED.moratorium_available,
    moratorium_details = EXCLUDED.moratorium_details,
    repayment_period = EXCLUDED.repayment_period,
    target_beneficiaries = EXCLUDED.target_beneficiaries,
    description = EXCLUDED.description,
    key_highlights = EXCLUDED.key_highlights,
    semantic_description = EXCLUDED.semantic_description,
    official_source = EXCLUDED.official_source,
    is_active = EXCLUDED.is_active,
    updated_at = NOW();

-- Ensure public read permissions are granted to anon and authenticated roles
GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON TABLE public.schemes TO anon, authenticated;
